# Generated by Django 4.2.6 on 2023-10-06 13:32

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CurrencyRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cbrf_id", models.CharField(max_length=10)),
                ("num_code", models.IntegerField()),
                ("char_code", models.CharField(max_length=3)),
                ("name", models.CharField(max_length=256)),
                ("nominal", models.IntegerField()),
                ("value", models.DecimalField(decimal_places=4, max_digits=12)),
                (
                    "previous_value",
                    models.DecimalField(decimal_places=4, max_digits=12),
                ),
                ("date", models.DateField()),
            ],
        ),
    ]
