# Generated by Django 4.2.6 on 2023-10-11 06:43

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("currencies", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="currencythreshold",
            unique_together={("user", "currency")},
        ),
    ]
